package sarah.mapreduce.balance;

import org.apache.hadoop.conf.Configuration;

import sarah.mapreduce.metrics.MapReduceSarahMetrics;
import sarah.metrics.CountedLongSarahMetric;
import sarah.metrics.SarahMetric;

public class BalanceSarahMetrics extends MapReduceSarahMetrics {

	// metrics generated by the balance tool
	public CountedLongSarahMetric recommendedNumberReducersForF = 
			new CountedLongSarahMetric("sarah.%func.number.reducers","undescribed");  
	public SarahMetric<?>[] balanceMetrics = {recommendedNumberReducersForF};
	
	private static BalanceSarahMetrics singleton;
	
	public BalanceSarahMetrics(Configuration conf) {
		super(conf);
		singleton = this;
		
	}
	
	public static BalanceSarahMetrics get() {
		return singleton;
	}
}
